### ISSUE TITLE
Prevent real module from getting executed on the browser

### ISSUE THREAD

**Issue by musjj** [ReactLibraries/storybook-addon-module-mock#19]
I'm trying to make a story for a component that imports a server-only function, like this:

```typescript
import * as dataGetters from "./get-data.ts";

export const Default: Story = {
  parameters: {
    moduleMock: {
      mock: () => {
        const getUser = createMock(dataGetters, "getUser");
        getUser.mockImplementation(() => Promise.resolve(undefined));

        return [db];
      },
    },
  }
}
```

But the module I'm trying to mock has side effects:

`get-data.ts`
```typescript
import { dbClient } from "my-orm";

const db = dbClient.connect(); // Connect to the database

export function getUser() {
  return db.user.findAll();
};
```

(this is a huge simplification)

But the story fails to build because the database client (obviously) doesn't work in the browser.

It looks like that the module was imported (causing the db client to be executed), before it could be mocked. Is there a way to make sure that the module never gets executed?

**Comment by ranisalt** [comment]
I don't know why you closed but this is still an issue. It mocks way too late, mocking must be executed before imports and not after.

[The way Storybook provides "mocks"](https://storybook.js.org/docs/writing-stories/mocking-data-and-modules/mocking-modules) is clunky and goes against code organization - plus it does not work at all - so I was looking forward to this addon
