### ISSUE TITLE
Can this be used to mock a single function?

### ISSUE THREAD

**Issue by jelling** [ReactLibraries/storybook-addon-module-mock#3]
Hey, thanks for making this. But is it possible to use this to mock a single function? 

This is what I'm trying to do: https://github.com/storybookjs/storybook/discussions/21848

**Comment by SoraKumo001** [comment]
Only mocked objects that have been `createMocked` will be mocked.

**Comment by jelling** [comment]
Sorry, but could you elaborate?

**Comment by SoraKumo001** [comment]
I am not sure what you want me to elaborate on, or what the intent of your question is.
Please do not throw your questions to others until you ask them.
