### ISSUE TITLE
404 on yarn/npm registry

### ISSUE THREAD

**Issue by taozhou-glean** [ReactLibraries/storybook-addon-module-mock#9]
404 from https://www.npmjs.com/package/storybook-addon-module-mock, maybe just npm issue

**Comment by taozhou-glean** [comment]
hmm i thought after left-pad outage, the npm will not directly depend on the source (github) and ensure that even the owner can not just delete the package to break all of their dependencies... (like read-only mode for all past versions)...

**Comment by taozhou-glean** [comment]
the latest commit and only commit in the past a few months, @SoraKumo001 is it possible to restore this asap ? thanks

**Comment by SoraKumo001** [comment]
I contacted npm support to restore it.
It seems to be fine now.

**Comment by taozhou-glean** [comment]
@SoraKumo001 thanks, can your provide a short summary on what happened ? for my own learning
